export const categories = [
  { value: 'web_development', label: 'Web Development' },
  { value: 'mobile_development', label: 'Mobile Development' },
  { value: 'desktop_development', label: 'Desktop Development' },
  { value: 'browser_extensions', label: 'Browser Extensions' },
  { value: 'automation_bots', label: 'Automation Bots' },
  { value: 'social_media_bots', label: 'Social Media Bots' },
  { value: 'scraping_monitoring', label: 'Scraping & Monitoring' },
  { value: 'blockchain_cryptocurrency', label: 'Blockchain & Cryptocurrency' },
  { value: 'ecommerce_automation', label: 'E-commerce Automation' },
  { value: 'game_development', label: 'Game Development' },
  { value: 'ui_ux_design', label: 'UI/UX Design' },
  { value: 'discord_telegram_bots', label: 'Discord & Telegram Bots' },
  { value: 'api_development', label: 'API Development' },
  { value: 'security_antibot', label: 'Security & Anti-bot' },
  { value: 'data_science_ml', label: 'Data Science & Machine Learning' },
  { value: 'account_generation', label: 'Account Generation' },
  { value: 'captcha_solving', label: 'Captcha Solving' },
  { value: 'proxy_vpn', label: 'Proxy & VPN' },
  { value: 'email_automation', label: 'Email Automation' },
  { value: '3d_rendering', label: '3D Rendering' },
  { value: 'other', label: 'Other' },
];
